CREATE TABLE [dbo].Challenger
(
	[Number] INT NOT NULL PRIMARY KEY, 
    [Name] NCHAR(100) NOT NULL, 
    [25] INT NULL DEFAULT 0, 
    [35] INT NULL DEFAULT 0, 
    [45] INT NULL DEFAULT 0, 
    [60] INT NULL DEFAULT 0, 
    [70] INT NULL DEFAULT 0, 
    [80] INT NULL DEFAULT 0, 
    [100] INT NULL DEFAULT 0
)
